# Generated by Django 2.1.5 on 2019-02-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0002_waterlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlevel',
            name='user',
        ),
        migrations.DeleteModel(
            name='WaterLevel',
        ),
    ]
