# Generated by Django 2.1.5 on 2019-02-06 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden_api', '0002_auto_20190205_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilmoisture',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
