# Generated by Django 2.1.5 on 2019-02-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_api', '0003_auto_20190206_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilmoisture',
            name='has_moisture',
            field=models.BooleanField(),
        ),
    ]
